// Canonical Resolume Arena OSC parameter paths — *baseline* set for a
// composition with one layer, one clip, no effects (per Resolume's docs).
// Real compositions add more layers/clips/effects; ResolumePanel combines
// this baseline with paths from the currently-loaded preset to give a high-
// signal autocomplete.
//
// Layer/clip/column/deck numbers shown as `1` are placeholders — users
// substitute the actual index when picking from the autocomplete. Resolume
// also accepts relative addresses like `/composition/selectedlayer/...` and
// `/composition/selectedclip/...` (a few common ones included below).

export const KNOWN_RESOLUME_PATHS: string[] = [
  // Composition
  '/composition/connectnextcolumn',
  '/composition/connectprevcolumn',
  '/composition/connectspecificcolumn',
  '/composition/audio/pan',
  '/composition/audio/volume',
  '/composition/bypassed',
  '/composition/direction',
  '/composition/disconnectall',
  '/composition/master',
  '/composition/name',
  '/composition/selectnextdeck',
  '/composition/selectprevdeck',
  '/composition/selectspecificdeck',
  '/composition/speed',
  '/composition/video/effects/transform/anchorx',
  '/composition/video/effects/transform/anchory',
  '/composition/video/effects/transform/anchorz',
  '/composition/video/effects/transform/bypassed',
  '/composition/video/effects/transform/positionx',
  '/composition/video/effects/transform/positiony',
  '/composition/video/effects/transform/rotationx',
  '/composition/video/effects/transform/rotationy',
  '/composition/video/effects/transform/rotationz',
  '/composition/video/effects/transform/scale',
  '/composition/video/effects/transform/scaleh',
  '/composition/video/effects/transform/scalew',
  '/composition/video/height',
  '/composition/video/opacity',
  '/composition/video/width',
  '/composition/dashboard/link1',
  '/composition/dashboard/link2',
  '/composition/dashboard/link3',
  '/composition/dashboard/link4',
  '/composition/dashboard/link5',
  '/composition/dashboard/link6',
  '/composition/dashboard/link7',
  '/composition/dashboard/link8',

  // Layer (replace /1/ with target layer index)
  '/composition/layers/1/audio/pan',
  '/composition/layers/1/audio/volume',
  '/composition/layers/1/autopilot',
  '/composition/layers/1/bypassed',
  '/composition/layers/1/clear',
  '/composition/layers/1/connectnextclip',
  '/composition/layers/1/connectprevclip',
  '/composition/layers/1/connectspecificclip',
  '/composition/layers/1/crossfadergroup',
  '/composition/layers/1/dashboard/link1',
  '/composition/layers/1/dashboard/link2',
  '/composition/layers/1/dashboard/link3',
  '/composition/layers/1/dashboard/link4',
  '/composition/layers/1/dashboard/link5',
  '/composition/layers/1/dashboard/link6',
  '/composition/layers/1/dashboard/link7',
  '/composition/layers/1/dashboard/link8',
  '/composition/layers/1/direction',
  '/composition/layers/1/faderstart',
  '/composition/layers/1/ignorecolumntrigger',
  '/composition/layers/1/maskmode',
  '/composition/layers/1/master',
  '/composition/layers/1/name',
  '/composition/layers/1/playmode',
  '/composition/layers/1/position',
  '/composition/layers/1/select',
  '/composition/layers/1/selected',
  '/composition/layers/1/smpte1quickselect',
  '/composition/layers/1/smpte2quickselect',
  '/composition/layers/1/solo',
  '/composition/layers/1/speed',
  '/composition/layers/1/transition/duration',
  '/composition/layers/1/triggerfirstcliponload',
  '/composition/layers/1/video/autosize',
  '/composition/layers/1/video/effects/transform/anchorx',
  '/composition/layers/1/video/effects/transform/anchory',
  '/composition/layers/1/video/effects/transform/anchorz',
  '/composition/layers/1/video/effects/transform/positionx',
  '/composition/layers/1/video/effects/transform/positiony',
  '/composition/layers/1/video/effects/transform/rotationx',
  '/composition/layers/1/video/effects/transform/rotationy',
  '/composition/layers/1/video/effects/transform/rotationz',
  '/composition/layers/1/video/effects/transform/scale',
  '/composition/layers/1/video/effects/transform/scaleh',
  '/composition/layers/1/video/effects/transform/scalew',
  '/composition/layers/1/video/height',
  '/composition/layers/1/video/mixer/blendmode',
  '/composition/layers/1/video/opacity',
  '/composition/layers/1/video/transition/mixer/blendmode',
  '/composition/layers/1/video/width',

  // Clip (replace /layers/1/ and /clips/1/ with target indices)
  '/composition/layers/1/clips/1/autopilot',
  '/composition/layers/1/clips/1/beatsnap',
  '/composition/layers/1/clips/1/cliptarget',
  '/composition/layers/1/clips/1/cliptriggerstyle',
  '/composition/layers/1/clips/1/connect',
  '/composition/layers/1/clips/1/connected',
  '/composition/layers/1/clips/1/dashboard/link1',
  '/composition/layers/1/clips/1/dashboard/link2',
  '/composition/layers/1/clips/1/dashboard/link3',
  '/composition/layers/1/clips/1/dashboard/link4',
  '/composition/layers/1/clips/1/dashboard/link5',
  '/composition/layers/1/clips/1/dashboard/link6',
  '/composition/layers/1/clips/1/dashboard/link7',
  '/composition/layers/1/clips/1/dashboard/link8',
  '/composition/layers/1/clips/1/faderstart',
  '/composition/layers/1/clips/1/ignorecolumntrigger',
  '/composition/layers/1/clips/1/name',
  '/composition/layers/1/clips/1/select',
  '/composition/layers/1/clips/1/selected',
  '/composition/layers/1/clips/1/transporttype',
  '/composition/layers/1/clips/1/transport/position',
  '/composition/layers/1/clips/1/transport/position/behaviour/speed',
  '/composition/layers/1/clips/1/transport/position/behaviour/dividetwo',
  '/composition/layers/1/clips/1/transport/position/behaviour/multiplytwo',
  '/composition/layers/1/clips/1/transport/position/behaviour/syncmode',
  '/composition/layers/1/clips/1/transport/position/behaviour/playdirection',
  '/composition/layers/1/clips/1/transport/position/behaviour/playmode',
  '/composition/layers/1/clips/1/transport/position/behaviour/playmodeaway',
  '/composition/layers/1/clips/1/video/mixer/blendmode',
  '/composition/layers/1/clips/1/video/opacity',
  '/composition/layers/1/clips/1/video/width',
  '/composition/layers/1/clips/1/video/height',
  '/composition/layers/1/clips/1/video/scaletofit',
  '/composition/layers/1/clips/1/video/rscale',
  '/composition/layers/1/clips/1/video/gscale',
  '/composition/layers/1/clips/1/video/bscale',
  '/composition/layers/1/clips/1/video/ascale',
  '/composition/layers/1/clips/1/transport/cuepoints/setparams/set1',
  '/composition/layers/1/clips/1/transport/cuepoints/jumpparams/jump1',
  '/composition/layers/1/clips/1/transport/cuepoints/setparams/set2',
  '/composition/layers/1/clips/1/transport/cuepoints/jumpparams/jump2',
  '/composition/layers/1/clips/1/transport/cuepoints/setparams/set3',
  '/composition/layers/1/clips/1/transport/cuepoints/jumpparams/jump3',
  '/composition/layers/1/clips/1/transport/cuepoints/setparams/set4',
  '/composition/layers/1/clips/1/transport/cuepoints/jumpparams/jump4',
  '/composition/layers/1/clips/1/transport/cuepoints/setparams/set5',
  '/composition/layers/1/clips/1/transport/cuepoints/jumpparams/jump5',
  '/composition/layers/1/clips/1/transport/cuepoints/setparams/set6',
  '/composition/layers/1/clips/1/transport/cuepoints/jumpparams/jump6',
  '/composition/layers/1/clips/1/video/effects/transform/anchorx',
  '/composition/layers/1/clips/1/video/effects/transform/anchory',
  '/composition/layers/1/clips/1/video/effects/transform/anchorz',
  '/composition/layers/1/clips/1/video/effects/transform/positionx',
  '/composition/layers/1/clips/1/video/effects/transform/positiony',
  '/composition/layers/1/clips/1/video/effects/transform/rotationx',
  '/composition/layers/1/clips/1/video/effects/transform/rotationy',
  '/composition/layers/1/clips/1/video/effects/transform/rotationz',
  '/composition/layers/1/clips/1/video/effects/transform/scale',
  '/composition/layers/1/clips/1/video/effects/transform/scaleh',
  '/composition/layers/1/clips/1/video/effects/transform/scalew',

  // Columns / Crossfader / Decks / BPM
  '/composition/columns/1/connect',
  '/composition/columns/1/name',
  '/composition/columns/1/selected',
  '/composition/crossfader/behaviour',
  '/composition/crossfader/curve',
  '/composition/crossfader/phase',
  '/composition/crossfader/sidea',
  '/composition/crossfader/sideb',
  '/composition/crossfader/video/mixer/blendmode',
  '/composition/decks/1/name',
  '/composition/decks/1/select',
  '/composition/tempocontroller/metronome',
  '/composition/tempocontroller/pause',
  '/composition/tempocontroller/resync',
  '/composition/tempocontroller/tempo',
  '/composition/tempocontroller/tempodec',
  '/composition/tempocontroller/tempodividetwo',
  '/composition/tempocontroller/tempoinc',
  '/composition/tempocontroller/tempomultiplytwo',
  '/composition/tempocontroller/tempopull',
  '/composition/tempocontroller/tempopush',
  '/composition/tempocontroller/tempotap',

  // SMPTE / UI / Audio / Recorder
  '/smptecontroller/smpte1offset',
  '/smptecontroller/smpte2offset',
  '/application/ui/clipsscrollhorizontal',
  '/application/ui/clipsscrollvertical',
  '/audiodevicemanager/params/fftinputgain',
  '/composition/recorder/record',

  // Selected-layer / selected-clip relative addresses (follow current selection)
  '/composition/selectedlayer/bypassed',
  '/composition/selectedlayer/clear',
  '/composition/selectedlayer/solo',
  '/composition/selectedlayer/master',
  '/composition/selectedlayer/speed',
  '/composition/selectedlayer/video/opacity',
  '/composition/selectedlayer/video/mixer/blendmode',
  '/composition/selectedclip/connect',
  '/composition/selectedclip/transport/position',
  '/composition/selectedclip/video/opacity',
  '/composition/selectedclip/video/mixer/blendmode',
  '/composition/selectedclip/transport/cuepoints/jumpparams/jump1',
];
